### ISSUE TITLE
font-awesome не включается в котлинскую сборку

### ISSUE THREAD

**Issue by alexvas** [gnefedev/kotlin-js-react#1]
Прежде всего, спасибо за понятный пример фулстэк-приложения. Удивительно, но на просторах интернета это единственный полный работающий пример, который я смог найти.

В данном конкретном примере есть небольшая недоработка, если запускать только его Котлиновую часть. Выпадашки используют `<span class="fa fa-fw fa-caret-down ui-clickable"></span>` библиотеку font awesome. 

Ссылка на css стиль есть в index.html:
  <link rel="stylesheet" type="text/css" href="/style/font-awesome.min.css">
а библиотека копируется из модулей ноды задачей prepareWeb.

Штука в том, что модуля font-awesome среди модулей ноды нет, по крайней мере, если запускать только котлиновскую часть проекта. Модуль primereact устанавливается, вероятно, из-за аннотации JsModule. А вот font-awesome приходится устанавливать нодой вручную. Может быть, по крайней мере, добавить какую-то инструкцию в README?

**Comment by gnefedev** [comment]
просто забыл "font-awesome": "^4.7.0" в зависимостях, добавил
